### ISSUE TITLE
SQL FCI FSx QuickStart Deployment Failure

### ISSUE THREAD

**Issue by Al-CloudBridge** [aws-quickstart/quickstart-microsoft-sql-fci-fsx#17]
Hi Guys

I'm getting a CloudFormation deployment failure with event: 
SSMWaitCondition | CREATE_FAILED | Received FAILURE signal with UniqueId i-09be100a7c4ebb961

SSM automation details show that the DSM modules are failing to install on the target EC2 instances:
1670dec0-a580-4594-a1cb-4d1964f6064b | 8 | InstallDSCModules | aws:runCommand | Failed

Parameters
commandLine: "./install-dsc-modules.ps1"
sourceInfo: "{"path": "https://aws-quickstart-eu-west-1.s3.eu-west-1.amazonaws.com/quickstart-microsoft-SqlFSx/scripts/install-dsc-modules.ps1"}"
sourceType: "S3"

CloudWatch logs show a failure to find the script that will install the DSM modules:

./install-dsc-modules.ps1 : The term './install-dsc-modules.ps1' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At C:\ProgramData\Amazon\SSM\InstanceData\i-074987453d0789e8f\document\orchestration\a87cdbe3-4e8c-44a1-92ab-9983fa903d
20\runPowerShellScript\_script.ps1:4 char:2
+  ./install-dsc-modules.ps1
+  ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./install-dsc-modules.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Here's the contents of the '_script.ps1' mentioned above:

 $directory = Convert-Path .
$env:PATH += ";$directory"
 ./install-dsc-modules.ps1
if ($?) {
    exit $LASTEXITCODE
} else {
    exit 255
} 

The target EC2 instances have access to S3 both via the internet and a VPC endpoint so i'm wondering if either the source location 'aws-quickstart-eu-west-1.s3.eu-west-1.amazonaws.com/quickstart-microsoft-SqlFSx/scripts/' or the script itself 'install-dsc-modules.ps1' no-longer exist.

I'm not able to reach "https://aws-quickstart-eu-west-1.s3.eu-west-1.amazonaws.com/quickstart-microsoft-SqlFSx/scripts/install-dsc-modules.ps1"

It's worth noting that the location for my copy of the Quick Starts assets (including the DSC script) 'https://aws-quickstart-eu-west-1.s3.eu-west-1.amazonaws.com/quickstart-microsoft-SqlFSx/scripts/' is determined by some Stack parameters which i'd left at their defaults (below):

QSS3BucketName: aws-quickstart
QSS3BucketRegion: us-east-1
QSS3KeyPrefix: quickstart-microsoft-SqlFSx/

However, i don't see any S3 bucket or subfolders matching that description in my account. 

Please can you advise?

Many thanks
Alan

**Comment by davmayd** [comment]
This is a problem with the default QSS3KeyPrefix value. It should be "quickstart-microsoft-sql-fci-fsx" rather than "quickstart-microsoft-sqlfsx". I'll get this fixed ASAP.
